// Code generated by a tool nobody has. DO NOT EDIT.
// the marker above is not prose

package directives

// The marker is matched whole, so a line joined onto it takes the file out
// of the form every tool that asks whether it is generated looks for.

// want +2 `comment-wrap: .* over 2 lines; .* takes 1`

// prose still
// fills in here
type Generated struct{}
